apiVersion: v1
kind: List
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: treesam
      app.kubernetes.io/component: treesam
      app.kubernetes.io/instance: treesam
    name: treesam
  spec:
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: treesam
    template:
      metadata:
        labels:
          deploymentconfig: treesam
      spec:
        containers:
        - image: treesam
          imagePullPolicy: Always
          name: treesam
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - treesam
        from:
          kind: ImageStreamTag
          name: treesam:test
      type: ImageChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: treesam
      app.kubernetes.io/component: treesam
      app.kubernetes.io/instance: treesam
    name: treesam
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: treesam
      app.kubernetes.io/component: treesam
      app.kubernetes.io/instance: treesam
    name: treesam
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: treesam
      weight: 100
    wildcardPolicy: None
